DROP TABLE HOTEL;
DROP TABLE SALA;
DROP TABLE PARTICIPANTE;

CREATE TABLE PARTICIPANTE (
    ID_ASOCIADO NUMBER(8),
    NOMBRE NVARCHAR2(50) NOT NULL,
    APELLIDO_P NVARCHAR2(50) NOT NULL,
    APELLIDO_M NVARCHAR2(50) NOT NULL,
    CONSTRAINT PARTICIPANTE_PK PRIMARY KEY(ID_ASOCIADO),
    CHECK (ID_ASOCIADO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
);

CREATE TABLE PAIS (
    ID_PAIS NUMBER(8) PRIMARY KEY,
    NOMBRE NVARCHAR2(30) NOT NULL
);

CREATE TABLE PARTIDA (
    ID_PARTIDA NUMBER(8) PRIMARY KEY
);

CREATE TABLE JORNADA (
    ID_JORNADA NUMBER(8) PRIMARY KEY
);

CREATE TABLE HOTEL (
    ID_HOTEL NUMBER(8) PRIMARY KEY,
    NOMBRE NVARCHAR2(30) NOT NULL,
    TELEFONO NUMBER(7) 
);

CREATE TABLE SALA (
    ID_SALA NUMBER(8) PRIMARY KEY,
    NOMBRE  NVARCHAR2(30) NOT NULL,
    CAPACIDAD NUMBER(3) NOT NULL
);